num_bins: 10
binning_method: 'equal_length'
img_dpi: 500
computation_type: 'cupy'
num_times: 3595
timesteps: '0:3'
num_freq: 20
freqsteps: '0:1'
filter_baselines_enabled: false
uv_range: [-1000, 1000]
theta_maj: 0.0441370233211219
theta_min: 0.0329175084774813
D: 30.75
precision: 'double'